### PR TITLE
Complete signin/signup with db

### LINKED ISSUE #13: [Setup]: Sign up / in Route
Route to sign in / up
fill logic behind

### PR DESCRIPTION
**Pull request by Benjicatch**
to make everything work perfectly, you need:
- a .env with this information : 'DATABASE_URL="postgresql://postgres:123@localhost:5434/nest?schema=public"'
- a .env.test with this information : 'DATABASE_URL="postgresql://postgres:123@localhost:5435/nest?schema=public"'
close #13

### CODE REVIEW

**Review by FoxaxeWasTaken — APPROVED** [review]
LGTM !

**Review by AlexGuillard — DISMISSED** [review]
ok

**Review by Kiya971 — APPROVED** [review]
:+1:

**Review by Pablodeibar — APPROVED** [review]
just the :goat:

**Review by Pablodeibar — APPROVED** [review]
:cn: number one

**Pull request merged**
