### PR TITLE
feat(deployement): add env var in dockerfile of mobile prod 

### PR DESCRIPTION
**Pull request by Miou-zora**
Linked to no issue.

It allow to set ip / port of mobile prod correctly for deployement

### CODE REVIEW

**Review by Pablodeibar — APPROVED** [review]
ok

**Review by AlexGuillard — DISMISSED** [review]
seems ok

**Review by AlexGuillard — APPROVED** [review]
ok

**Review by Pablodeibar — APPROVED** [review]
ok

**Pull request merged**
