### PR TITLE
feat( Modal edit/add  + AddButton (31 > main)): create modal component and AddButton

### LINKED ISSUE #31: Create modal component
Create a modal to edit and create an area following the Figma it looks like this for add

Image

and like this for edit

Image

### PR DESCRIPTION
**Pull request by Pablodeibar**
Closes #31 
i created Palette.css which **YOU HAVE TO REFER** if you use color on front
here is what it looks like its ugly but respect the palette we choose
image
image
Closes #31

### CODE REVIEW

**Review by AlexGuillard — CHANGES_REQUESTED** [review]
change color with the palette:
#191825
#918ea5
#463a8d
#929094

**Review by AlexGuillard — APPROVED** [review]
ok

**Review by FoxaxeWasTaken — DISMISSED** [review]
LGTM !

**Review by AlexGuillard — APPROVED** [review]
ok

**Review by Miou-zora — APPROVED** [review]
I didn't read anything, and they forced me to approve this PR - Corneille

**Pull request merged**
