### PR TITLE
feat(apk): expose apk in web

### LINKED ISSUE #95: apk app
on route http://localhost:8081/client.apk, give the android application

### PR DESCRIPTION
**Pull request by Miou-zora**
Linked to:
- close #95

### CODE REVIEW

**Comment by Benjicatch** [comment]
if you go to http://localhost:8081/client.apk, it download the apk ?

**Comment by Miou-zora** [comment]
For me yes

**Review by AlexGuillard — APPROVED** [review]
ok

**Review by Pablodeibar — APPROVED** [review]
ok

**Comment by Benjicatch** [comment]
if i'm going to  http://localhost:8081/client.apk, i'm supposed to have the mobile application to be download, but it's not the case

**Review by Kiya971 — APPROVED** [review]

**Pull request merged**
