### PR TITLE
feat(DB): 24 setup database

### LINKED ISSUE #24: setup database
Table USER for DB
- ID
- EMAIL
- PASSWORD

Table AREA
- ID -> Primary Key
- ID_USER -> External Key
- NAME -> Text
- ID_ACTION -> External Key
- ID_REACTION -> External Key

Table SERVICES
- ID
- ID_USER
- TOKEN
- ENUM

Table ACTION 
- SERVICE_IDIX
- NAME
- ID

Table REACTION
- SERVICE_ID
- NAME
- ID

### PR DESCRIPTION
**Pull request by Benjicatch**
close #24 
here is the result of the sql:
image
to make the database work, you need to lauch the docker compose
you also need to have a .env in the server folder with this information : 
- DATABASE_URL="postgresql://postgres:123@localhost:5434/nest?schema=public"

### CODE REVIEW

**Review by Pablodeibar — APPROVED** [review]
We need parameter like string on area to use infos from user

**Review by Pablodeibar — CHANGES_REQUESTED** [review]
We need parameter like string on area to use infos from user

**Review by FoxaxeWasTaken — APPROVED** [review]
LGTM !

**Review by Pablodeibar — COMMENTED** [review]
good

**Review by Pablodeibar — APPROVED** [review]

**Pull request merged**
